- name: run playbook on localhost
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: install epel-repo
      yum:
       name: epel-release
       state: present
    - name: install list of packages
      yum:
       name: "{{ packages }}"
       state: latest
      vars:
       packages:
        - gcc
        - inotify-tools
        - bind-utils
    - rpm_key:
       state: present
       key: http://www.atomicrocketturtle.com/RPM-GPG-KEY.art.txt
    - name: install Atomic repo
      yum:
       name: /root/ansible/atomic-release-1.0-21.el7.art.noarch.rpm
       state: present
    - name: install ossec
      yum:
       name: ossec-hids-agent
       state: latest
      